 - name: Deploy to EC2
   hosts: localhost
   connection: local

   tasks:
    - name: Launch EC instance
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-d3c7fd9e
        assign_public_ip: yes
        wait: yes
        count: 2
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{session_token}}" 